### ISSUE TITLE
xml_str2json gives syntax error on Firefox

### ISSUE THREAD

**Issue by blakemcbride** [abdmob/x2js#13]
I am using Firefox 43.0 and X2JS 1.2.0 on a current 64 bit Linux box.  Everything works fine on Chrome.  When I run the following code on Firefox it gives me a syntax error in the console of their debugger (F12):

```
var x2js = new X2JS();
var xmlText = "<MyRoot><test>Success</test><test2><item>val1</item><item>val2</item></test2></MyRoot>";
var jsonObj = x2js.xml_str2json( xmlText );
```

I also get a syntax error when I run your similar fiddle.  The line referenced is the first line of the html file.  (which contains  <!DOCTYPE html>   ).  Not sure what to do.

Thanks!

**Comment by blakemcbride** [comment]
See:  https://github.com/dkdndes/x2js/issues/32

The changes suggested at the bottom fixed the problem for me.

**Comment by abdolence** [comment]
It's already fixed in 1.2.0.
I've just checked again it with https://jsfiddle.net/fjosfLbh/2/
in Firefox 43.0.4

**Comment by lourot** [comment]
I still have the issue with https://jsfiddle.net/fjosfLbh/2/ (using x2js 1.2.0) on Firefox 45.0.
Indeed the patch pointed by @blakemcbride solves the issue.

**Comment by sachi-d** [comment]
I faced the same issue with Firefox 49.0.2 and the  patch   #(https://github.com/dkdndes/x2js/issues/32) by @blakemcbride fixed it. @abdmob might want to check it again.
